name: prafullit-project

services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ./nginx-data:/data
      - ./nginx-letsencrypt:/etc/letsencrypt
      - ./nginx-snippets:/snippets:ro
    environment:
      TZ: 'Asia/Kolkata'
  
  app:
    build: .
    container_name: streamlit-app
    ports:
      - "8080:8080"
    restart: unless-stopped
